image: node:12.22.6-alpine
stages:
  - lint
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/
    - node_modules/

lint:
  stage: lint
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run lint-ci
  artifacts:
    reports:
      codequality: gl-codequality.json


test:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run test-ci
