image: node:12.22.6-alpine
stages:
  - lint
  - test
  - build

include:
  - template: Code-Quality.gitlab-ci.yml

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/
    - node_modules/

lint:
  stage: lint
  before_script:
    - yarn install --frozen-lockfile --cache-folder .npm
  script:
    - yarn lint-ci
  artifacts:
    reports:
      codequality: gl-codequality.json

test:
  stage: test
  before_script:
    - yarn install --frozen-lockfile --cache-folder .npm
  script:
    - yarn test-ci

build:
  stage: build
  before_script:
    - yarn install --frozen-lockfile --cache-folder .npm
  script:
    - yarn build-all
