name: Deploy to Firebase Functions on merge
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile && yarn build functions
      - name: Deploy firebase functions
        run: yarn firebase deploy --only functions -m "Workflow $GITHUB_WORKFLOW, action $GITHUB_ACTION" --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MACHI_KORO_DEV }}"