name: Deploy to Firebase Functions on merge
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile && yarn build functions
      - name: Deploy firebase functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P dev --only functions -m "Workflow $GITHUB_WORKFLOW, action $GITHUB_ACTION"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MACHI_KORO_DEV }}