name: Deploy Firebase rules on merge
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: yarn add -g firebase-tools
      - name: Deploy firebase rules
        run: yarn firebase deploy --only database,firestore,storage -m "Workflow $GITHUB_WORKFLOW, action $GITHUB_ACTION" --token "${{ secrets.FIREBASE_TOKEN_MACHI_KORO_DEV }}"