name: Quality check
on:
  push:
    branches: [main]

jobs:
  # TODO?: separete into three jobs
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn nx affected --target=lint --parallel=3
      - run: yarn nx affected --target=build --parallel=3
      - run: yarn nx affected --target=test --parallel=2